export { default as StudentForm } from './StudentForm';
export { default as StudentFormEdit } from './StudentFormEdit';
export { default as TeacherForm } from './TeacherForm';
export { default as TeacherFormEdit } from './TeacherFormEdit';
export { default as DepartmentForm } from './DepartmentForm';
export { default as DepartmentFormEdit } from './DepartmentFormEdit';
export { default as SpecialtyForm } from './SpecialtyForm';
export { default as SpecialtyFormEdit } from './SpecialtyFormEdit';
export { default as CourseForm } from './CourseForm';
export { default as CourseFormEdit } from './CourseFormEdit';
export { default as StaffCourseForm } from './StaffCourseForm';
export { default as StaffCourseFormEdit } from './StaffCourseFormEdit';
export { default as ProgramForm } from './ProgramForm';
export { default as ProgramFormEdit } from './ProgramFormEdit';
export { default as MarkTableFormCA } from './MarkTableFormCA';
export { default as MarkTableFormExam } from './MarkTableFormExam';
export { default as MarkTableFormPreMock } from './MarkTableFormPreMock';
export { default as MarkTableFormMock } from './MarkTableFormMock';
export { default as StaffReviewForm } from './StaffReviewForm';
export { default as PollForm } from './PollForm';
export { default as PollFormEdit } from './PollFormEdit';
// export { default as AcademicYearForm } from './AcademicYearForm';

export { default as GroupForm } from './GroupForm';
export { default as GroupFormEdit } from './GroupFormEdit';
export { default as TimetableForm } from './TimetableForm';
export { default as FormBsForm } from './FormBsForm';
