export const commingUp = [
	'/students/view',
	'/teachers/view',
	'/departments/view',
	'/specialty/view',
	'/specialties/view',
	'/accounts/fees-collection',
	'/accounts/expenses',
	'/accounts/salary',
	'/accounts/add-fees',
	'/accounts/add-expenses',
	'/accounts/add-salary',
	'/holiday',
	'/exam-list',
	'/events',
	'/time-table',
	'/library',
	'/settings',
	'/hostel',
	'/transport',
	'/blog/view',
	'/blog/add',
	// '/marks/:courseID/add',
	'/marks/:courseID/edit',
];
